export const endpoints = {
  api: {
    base: () => '/api',
  },
  auth: {
    register: () => '/api/auth/register',
    login: () => '/api/auth/login',
    logout: () => '/api/auth/logout',
    me: () => '/api/auth/me',
    changePassword: () => '/api/auth/change-password',
  },
  staffs: {
    getAll: () => '/api/staffs',
    getById: id => `/api/staffs/${id}`,
    create: () => '/api/staffs',
    update: id => `/api/staffs/${id}`,
    softDelete: id => `/api/staffs/${id}/soft-delete`,
    delete: id => `/api/staffs/${id}`,
  },
  stations: {
    getAll: () => '/api/stations',
    getById: id => `/api/stations/${id}`,
    create: () => '/api/stations',
    update: id => `/api/stations/${id}`,
    delete: id => `/api/stations/${id}`,
    softDelete: id => `/api/stations/soft-delete/${id}`,
    getUnavailable: () => '/api/stations/unavailable',
    getVehicles: stationId => `/api/stations/${stationId}/vehicles`,
    getStaff: stationId => `/api/stations/${stationId}/staff`,
  },
  vehicles: {
    getAll: () => '/api/vehicles',
    getById: id => `/api/vehicles/${id}`,
    create: () => '/api/vehicles',
    update: id => `/api/vehicles/${id}`,
    softDelete: id => `/api/vehicles/soft-delete/${id}`,
    delete: id => `/api/vehicles/${id}`,
    uploadImage: vehicleId => `/api/vehicles/${vehicleId}/images`,
    getImages: vehicleId => `/api/vehicles/${vehicleId}/images`,
    deleteImage: (vehicleId, imageId) =>
      `/api/vehicles/${vehicleId}/images/${imageId}`,
  },
  documents: {
    upload: () => '/api/documents/upload',
    myDocuments: () => '/api/documents/my-documents',
    getAll: () => '/api/documents/all',
    delete: id => `/api/documents/${id}`,
    verify: id => `/api/documents/${id}/verify`,
  },
  renters: {
    getAll: () => '/api/renters',
    getById: id => `/api/renters/${id}`,
    update: id => `/api/renters/${id}`,
    delete: id => `/api/renters/${id}`,
    create: () => '/api/renters',
    softDelete: id => `/api/renters/${id}/soft-delete`,
  },
  promotions: {
    getAll: () => '/api/promotions',
    getById: id => `/api/promotions/${id}`,
    getByCode: code => `/api/promotions/code/${code}`,
    getActive: () => '/api/promotions/active',
    create: () => '/api/promotions',
    update: id => `/api/promotions/${id}`,
    delete: id => `/api/promotions/${id}`,
  },
  assignments: {
    getAll: () => '/api/assignments',
    getById: id => `/api/assignments/${id}`,
    getByStaffId: staffId => `/api/assignments/staff/${staffId}`,
    create: () => '/api/assignments',
    update: id => `/api/assignments/${id}`,
    delete: id => `/api/assignments/${id}`,
    getUnassignedStaff: () => '/api/assignments/unassigned-staff',
  },
};
